export const AUTH_USERS_REQUEST = "AUTH_USERS_REQUEST";
export const AUTH_USERS_SUCCESS = "AUTH_USERS_SUCCESS";
export const AUTH_USERS_FAILURE = "AUTH_USERS_FAILURE";
export const AUTH_USERS_LOGOUT = "AUTH_USERS_LOGOUT";
