export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAILURE = "CART_ADD_FAILURE";
export const CART_DECREMENT_REQUEST = "CART_DECREMENT_REQUEST";
export const CART_DECREMENT_SUCCESS = "CART_DECREMENT_SUCCESS";
export const CART_DECREMENT_FAILURE = "CART_DECREMENT_FAILURE";
